# Generated by Django 4.2.3 on 2023-07-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_order_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addess',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Order',
            new_name='order',
        ),
    ]
